### ISSUE TITLE
Feature Request: SWADE Compatibility

### ISSUE THREAD

**Issue by Deadlander** [Saibot393/LocknKey#74] opened 2023-12-26 23:37 UTC
Is it possible to add the SWADE system for Lockpicking and door forcing?

**Comment by Saibot393** [comment] 2023-12-27 08:10
Sure, i will look into it. Could you give me rough run down of how these rolls would work in SWADE?

**Comment by Deadlander** [comment] 2023-12-29 11:13
Sure. Down and dirty, it is an open-ended dice system. Each time someone rolls a skill, they roll the skill die, plus a wild die (basically a bonus die), keeping the highest of the two. 

The skills that would be used in this case (and their SWADE ID or SWID) would be:
Thievery (SWID: thievery ) and Hacking (SWID: hacking ) for lockpicking.
Athletics (SWID: athletics ) for breaking down doors or forcing a lock.

In the SWADE System channel of the Foundry Discord, the most helpful would be either FloRad or ChaosOS if you need help with the system side of things. And you can blame it on me (They know me as jamesknightsotsmithdinnertablem, my Discord ID).

**Comment by Saibot393** [comment] 2024-01-08 18:44
I have released support for SWADE with v2.4.3. I will leave this issue open for now, in case something doesn't work as intended or there are questions

**Comment by Saibot393** [comment] 2024-01-21 12:44
Unless i hear otherwise i will assume that this issue has been solved and close it soon.

**Comment by Deadlander** [comment] 2024-01-23 22:07
Sorry, I did not get a notification about this! I will check things out as soon as I can and will get back to you!

**Comment by Deadlander** [comment] 2024-03-15 06:54
I apologize for the late response, but it is indeed working well!

**Comment by Saibot393** [comment] 2024-03-15 07:49
no problem, good to hear that it works

**Closed by Saibot393** 2024-03-15 07:49 UTC
Labels: enhancement
