### ISSUE TITLE
Compatibility Issue with Monk's Enhanced Journal

### ISSUE THREAD

**Issue by CasualTerror** [Saibot393/LocknKey#17] opened 2023-08-16 02:16 UTC
I got the error-
libWrapper: module Monk's Enhanced Journal and module Lock & Key modify the same FoundryVTT functionality and are more likely to conflict. foundry.js:68050 

On another note when I disable Monk's Enhanced Journal and I test the module as a player I can't unlock, pick, or break a locked door. I can't do anything. I've tried the macros and I've tried right-clicking. nothing.

**Comment by Saibot393** [comment] 2023-08-16 06:34
The first part with the warning only show up becaused both modules use a similar control sceme in some way meaning it could theoretically conflict. As far as i know though, there are no concrete issues related to this. 

I will look into the second problem, which game system are you using?

**Comment by Saibot393** [comment] 2023-08-19 21:38
After some testing i was not able replicate this behaviour (the module not working after uninstalling Monk's Enhanced Journal). Which foundry version are you using and are there any error messages in the console (F12) when this happens?

**Comment by ottyn** [comment] 2023-08-21 20:57
I'm getting the same LibWrapper warning about Enhanced Journals, but everything appears to be working correctly from my testing leaving Enhanced Journals enabled.  As an aside, Monk had the same warning popping up between his own modules, Enhanced Journals and Combat Details, and released a fix today for them that seems to have resolved it.  Still getting the warning for Lock & Key/Enhanced Journals after the update though.

**Comment by Saibot393** [comment] 2023-08-21 21:30
Just released v1.9.3 that should fix this warning, it however just tells the the libwrapper module to suppress it so any bugs that could appear still will appear

**Comment by Saibot393** [comment] 2023-08-31 21:22
Is there still any compatibility problem with Monk's Enhanced Journal? If not i will close this issue soon.

**Comment by CasualTerror** [comment] 2023-09-02 01:59
I don't think that Monk's Enhanced Journal is the issue now. I just can't get the module to work in 5e. I'm running Foundry v11.308. I can make a key but when I try to use the key by using the macro nothing happens and the hotkey just tries to open the open door again but says it is locked.

**Comment by Saibot393** [comment] 2023-09-02 08:46
The behaviour of the macro is expected as it only works for players (is asume you are loged in as a GM). The behaviour of the key (K) however is strange. Few questions:
-Do any errors show up in the console when using the key?
-Which modules are you using?

If you want you can send me your world file, then i can have a closer look at the problem

**Comment by CasualTerror** [comment] 2023-09-03 17:28
I'm testing it by logging in as a player. I've tried with just Lock & Key on and I was able to roll to break the lock. to pick the lock it said that I didn't have lock picks but I did have thieves' tools. and I had the key to the door and nothing happened, no error just nothing. I also tried Find the Culprit and it worked all the way through and thought the issue was a module that I added yesterday but I've had the issue longer.

Here is my long list of modules: 
### Active Modules
5e Encounter Builder v0.4.1
Active-Auras v0.7.5 [Bugs URL](https://github.com/kandashi/Active-Auras/issues)
Active Token Effects v0.6.2 [Bugs URL](https://github.com/kandashi/Active-Token-Lighting/issues)
Ammo Tracker v0.3.3
Anonymous v1.4.2 [Bugs URL](https://github.com/reonZ/anonymous/issues)
Argon - Combat HUD v1.7.8
Autocomplete Whisper v1.0.5
Automatic Journal Icon Numbers vv1.9.0 [Bugs URL](https://gitlab.com/tiwato/journal_icon_numbers/-/issues)
Auto-Rotate vv1.3.16 [Bugs URL](https://github.com/Varriount/fvtt-autorotate/issues)
Break Time v11.02 [Bugs URL](https://github.com/ironmonk88/breaktime/issues)
Build-a-Bonus v11.2.2
Carousel Combat Tracker v2.5.1
Cautious Gamemaster's Pack v1.4.1
Character Actions List dnd5e v6.1.1 [Bugs URL](https://github.com/eastcw/foundryvtt-dnd5eCharacterActions/issues)
Compact DnDBeyond 5e Character Sheet v2.3.3 [Bugs URL](https://github.com/eastcw/foundryvtt-compactBeyond5eSheet/issues)
Chat Images v3.2
Chat Message Accessibility Indicators v1.0.0
Cleaner sheet title bar v1.5.1
Colored Folder Contents v2.0.1 [Bugs URL](https://raw.githubusercontent.com/dor-fvtt-released-modules/colored-folder-contents/issues)
Combat Enhancements v1.2.2
Combat Estimate - How dead are we? v1.0.28
Combat Focus v1.4.2 [Bugs URL](https://github.com/Oromis/foundry-combat-focus/issues)
DDB-Importer: A D&D Beyond Integrator v3.4.63
DFreds Convenient Effects v5.1.0 [Bugs URL](https://github.com/DFreds/dfreds-convenient-effects/issues)
DFreds Droppables v3.0.1 [Bugs URL](https://github.com/DFreds/dfreds-droppables/issues)
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Dice So Nice - Weighted Companion Cube Dice Set v1.0.4
Entice with Dice so Nice v0.1.0
Fudge O' Plenty v1.0.0
Handyfon's Dice Addiction v1.1.0
Lordu's Custom Dice for Dice So Nice v0.39
Talis Dice v1.0.6
WikiRole for Dice So Nice v0.0.1
Dice Tray v1.5.3
dlopen v1.0
VuePort: Let the Light in! v1.1
The Forge: Compendium Library v1.3.4 [Bugs URL](https://github.com/ForgeVTT/forge-compendium-browser/issues)
Basic Rules v0.3.24
DND5E Scriplets - 5E QOL bits and pieces v0.10.1
Drag Ruler v1.13.8 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
Dynamic effects using Active Effects v11.0.11 [Bugs URL](https://gitlab.com/tposney/dae/-/issues)
Midi QOL v11.0.14.2 [Bugs URL](https://gitlab.com/tposney/midi-qol/-/issues)
Chris's Premades v0.5.65
Midi QOL - Challenge Mode Armor Display v1.0.4 [Bugs URL](https://github.com/mouse0270/midi-challenge-mode-armor/issues)
Midi SRD v11.0.0 [Bugs URL](https://github.com/thatlonelybugbear/midi-srd/issues)
Boss Loot Interactive Magic Items, Free Pack v11.0.3 [Bugs URL](https://github.com/boss-loot/FoundryVTT-Items)
EEEG-Importer v1.1.7
Effect Macro v11.0.1
Find the culprit v1.4.6 [Bugs URL](https://github.com/Moerill/fvtt-find-the-culprit/issues)
Force Client Settings v2.3.2 [Bugs URL](https://gitlab.com/kimitsu_desu/force-client-settings/-/issues)
Foundry Community Macros v10.4 [Bugs URL](https://github.com/foundry-vtt-community/macros/issues)
Foundry Community Tables v11.0 [Bugs URL](https://github.com/foundry-vtt-community/tables/issues)
Foundry VTT Anniversary Dice Set by The Rollsmith v1.0.1 [Bugs URL](https://therollsmith.com/contact/)
FoundryVTT Arms Reach v2.2.14 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
FoundryVTT Cards v1.3.0 [Bugs URL](https://github.com/jcolson/foundryvtt_cards/issues)
FXMaster v4.0.2 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
Give item to another player v1.12.2 [Bugs URL](https://github.com/Sepichat/FoundryVTT-GiveItem/issues)
GM Notes v8.8
GM Screen v4.0.4 [Bugs URL](https://github.com/ElfFriend-DnD/foundryvtt-gmScreen/issues)
Health Estimate v31.4 [Bugs URL](https://github.com/mclemente/healthEstimate/issues)
Hey, Wait! v0.7.5
Item Macro v1.9.0+1
Item Piles v2.7.10 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
JB2A - Jules and Ben's Animated Assets - Free Content v0.6.0
JB2A - Patreon Complete Collection v0.4.6
Ace Library v1.8.3 [Bugs URL](https://github.com/arcanistzed/acelib/issues/new/choose)
Chat Commander v2.0.1 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-chat-command-lib/-/issues)
lib - Color Settings v2.9.1
libWrapper v1.12.13.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
Stream Utils v2.8.0
Link Item and Resource DnD5e v2.1.0 [Bugs URL](https://github.com/ElfFriend-DnD/foundryvtt-link-item-resource-5e/issues)
Lock & Key v1.9.7 [Bugs URL](https://github.com/Saibot393/LocknKey/issues)
LootsheetNPC5e v3.6.1
Magic Items v3.0.0
Forgotten Adventures Battlemaps v1.0.38
Mass Edit v1.44.8
Merchant Sheet NPC v2.9.1
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Active Tile Triggers v11.06 [Bugs URL](https://github.com/ironmonk88/monks-active-tiles/issues)
Monk's Chat Timer v11.01 [Bugs URL](https://github.com/ironmonk88/monks-chat-timer/issues)
Monk's Combat Details v11.06 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v11.01 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Enhanced Journal v11.07 [Bugs URL](https://github.com/ironmonk88/monks-enhanced-journal/issues)
Monk's Hotbar Expansion v10.1 [Bugs URL](https://github.com/ironmonk88/hotbar-expansion/issues)
Monk's Little Details v11.05 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's Player Settings v11.01 [Bugs URL](https://github.com/ironmonk88/monks-player-settings/issues)
Monk's Scene Navigation v11.02 [Bugs URL](https://github.com/ironmonk88/monks-scene-navigation/issues)
Monk's TokenBar v11.02 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)
Monk's Wall Enhancement v11.02 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Multiface Tiles v1.0.11
Navigation Name v0.1.03
Optional Rules for Dnd5e v0.5.2
Ownership Viewer v11.2 [Bugs URL](https://github.com/mclemente/fvtt-module-permission-viewer/issues)
Pin Cushion v1.9.1 [Bugs URL](https://github.com/p4535992/foundryvtt-pin-cushion/issues)
Pin Fixer v1.2.2 [Bugs URL](https://github.com/zeel01/pin-fixer/issues)
Ping Logger v1.2.20 [Bugs URL](https://github.com/mawburn/foundry-ping-logger/issues)
Polyglot v2.1.6 [Bugs URL](https://github.com/mclemente/fvtt-module-polyglot/issues)
Pushable tokens v10.0.2
Quick Encounters v1.2.0 [Bugs URL](https://github.com/spetzel2020/quick-encounters/issues)
Quick Insert - Search Widget v2.8.3 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
Revealed Notes Manager v2.4.3
Revised Weapons & Equipment v1.3.0
Sane Magical Item Prices Compendium v0.7.1
Sequencer v3.1.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.66
Simbul's Athenaeum v1.0.5
Simbul's Cover Calculator v1.4.4
Simple Calendar v2.3.20 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
About Time v11.0.1 [Bugs URL](https://gitlab.com/tposney/about-time/-/issues)
SmallTime v1.18.0 [Bugs URL](https://github.com/unsoluble/smalltime/issues)
Smart Doors v1.4.1 [Bugs URL](https://github.com/manuelVo/foundryvtt-smart-doors/issues)
Smart Target v1.0.1 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
Stream View v2.0.1 [Bugs URL](https://github.com/sPOiDar/fvtt-module-stream-view/issues)
Tagger v1.4.5 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Tagger/issues)
Template Macro v11.0.0
The Forge v1.10
TheRipper93's Module Hub v1.1
Tidy5e Sheet v0.9.18 [Bugs URL](https://github.com/sdenec/tidy5e-sheet/issues)
Times Up v11.0.3 [Bugs URL](https://gitlab.com/tposney/times-up/-/issues)
Token Attacher vv4.5.13
Token Factions vv0.4.8 [Bugs URL](https://github.com/p4535992/foundryvtt-token-factions/issues)
Tokenizer v4.2.5
Token Magic FX v0.6.4.1
Token Mold v2.20.3 [Bugs URL](https://github.com/Moerill/token-mold/issues)
Token Variant Art v4.53.1 [Bugs URL](https://github.com/Aedif/TokenVariants/issues)
Minimal UI v1.6.5
Remote Highlight UI v2.0.0 [Bugs URL](https://github.com/shemetz/remote-highlight-ui/issues)
Visual Active Effects v11.0.5
Walled Templates v0.6.6
Wall Height v5.0.3
Levels v4.2
Warp Gate v1.18.1
Window Controls v1.11.2
World Anvil Integration v1.4.4
World Anvil Integration - Actors v1.0.2
World Anvil Integration - Custom secrets v1.0.3

**Comment by Saibot393** [comment] 2023-09-03 18:00
I am fairly certain, that the bug is caused by one of the modules somehow invalidating the way i access a tokens inventory. Could you try to paste this line: canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items in the console (F12) while having a token (with at least one item in its inventory) selected and posting the result of that? That would help me confirm my suspicion. I will look through the modules to see if i can identify the problem.

**Comment by CasualTerror** [comment] 2023-09-03 19:05
This is what I got. 
![image](https://github.com/Saibot393/LocknKey/assets/32625656/4f08d9bc-7030-4b12-8a02-26cbd5513628)

**Comment by Saibot393** [comment] 2023-09-03 19:44
I just tried to replicate the bug with almost all of these modules installed (some did not seem to be available on v11) but could not get it to work or rather not work. I would guess that there is some specific setting in one of the modules that causes lock and key to fail. The only solution i can think of would be you sending me your raw world file (without all the audio/image assets) so that i can have a closer look at the issue.

**Comment by Saibot393** [comment] 2023-09-23 20:44
I just thought of another possible cause of this bug. Could try pasting this line: canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.map(vitem => vitem.quantity) into the console, again while having a token selected, preferably one with only a key in the inventory?

**Comment by Geektasticdad** [comment] 2023-11-25 16:19
> I just thought of another possible cause of this bug. Could try pasting this line: `canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.map(vitem => vitem.quantity)` into the console, again while having a token selected, preferably one with only a key in the inventory?

I'm having the same problem, and I've used the ID of the character's Thieves' Tools as well as the compendium IDs. I ran the command you asked about and got the following results:

`(58) [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]`

**Comment by Saibot393** [comment] 2023-11-25 16:21
Thank you, thats helpful. Are you also using the D&D 5e system?

**Comment by Saibot393** [comment] 2023-11-25 16:23
I am so sorry, i had a typo in the command. Could you try again with `canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.map(vitem => vitem.system.quantity)`

**Comment by Geektasticdad** [comment] 2023-11-25 16:25
> I am so sorry, i had a typo in the command. Could you try again with `canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.map(vitem => vitem.system.quantity)`

That gave me this response

`(58) [1, 1, 1, 1, 1, 1, 6, 5, 1, 1, 1, 3, 1, 1, 1, 1, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]`

**Comment by Geektasticdad** [comment] 2023-11-25 16:26
> Thank you, thats helpful. Are you also using the D&D 5e system? Also which Foundry and which System version are you running?

Yes I'm using the D&D 5e system, and just recently updated to 2.4.0

**Comment by Saibot393** [comment] 2023-11-25 16:29
Could you send me a screenshot of the tokens inventory?

**Comment by Geektasticdad** [comment] 2023-11-25 16:47
> Could you send me a screenshot of the tokens inventory?

![chrome_iLvk9OQdgO](https://github.com/Saibot393/LocknKey/assets/73676044/2888f469-1067-4874-b5b3-56ce14547b24)

**Comment by Saibot393** [comment] 2023-11-25 17:01
Assuming you have the popup texts turned on (both in Lock & Key and in core Foundry), does the "No lock pick" text popup when you try to pick a lock? If so, could you enter this `console.log({sID : canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.find(vitem => vitem.name == "Thieves' Tools").flags.core?.sourceId, ID :  canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.find(vitem => vitem.name == "Thieves' Tools").id, worldid : game.settings.get("LocknKey", "LockPickItem").split(";")})` into the console and send me the (uncollapsed) ouput

**Comment by Geektasticdad** [comment] 2023-11-25 17:21
> Assuming you have the popup texts turned on (both in Lock & Key and in core Foundry), does the "No lock pick" text popup when you try to pick a lock? If so, could you enter this `console.log({sID : canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.find(vitem => vitem.name == "Thieves' Tools").flags.core?.sourceId, ID : canvas.tokens.controlled.map(pToken => pToken.document)[0].actor.items.find(vitem => vitem.name == "Thieves' Tools").id, worldid : game.settings.get("LocknKey", "LockPickItem").split(";")})` into the console and send me the (uncollapsed) ouput

Here you go

```
{sID: undefined, ID: 'wEnSmJhip5sej512', worldid: Array(2)}
ID
: 
"wEnSmJhip5sej512"
sID
: 
undefined
worldid
: 
(2) ['99NTJQbKtlSdFXc2', 'woWZ1sO5IUVGzo58']
[[Prototype]]
: 
Object
```

**Comment by Saibot393** [comment] 2023-11-25 17:23
Thank you, i see the problem now, how did you create the Thieves' Tools?

**Comment by Geektasticdad** [comment] 2023-11-25 17:25
> Thank you, i see the problem now, how did you create the Thieves' Tools?

I'm pretty sure I pulled it into the character's sheet from a compendium (either DnD5e SRD Content or D&D Beyond import).

**Comment by Geektasticdad** [comment] 2023-11-25 17:34
It might be possible that it imported from D&D Beyond using DDB-Importer created by MrPrimate. I don't sync inventory anymore, but could that be why it's being wonky?

**Comment by Saibot393** [comment] 2023-11-25 17:36
The problem is, that the source id (`flags.core.sourceId`) is set to unidentified, which prevents Lock & Key from finding the Thieves' Tools. I am currently looking for an alternative way of getting the source id.

**Comment by Geektasticdad** [comment] 2023-11-25 17:43
> The problem is, that the source id (`flags.core.sourceId`) is set to unidentified, which prevents Lock & Key from finding the Thieves' Tools. I am currently looking for an alternative way of getting the source id.

Okay, I figured out the Thieves' Tools I added to the character came from the DnDBeyond Compendium. I replaced it with the Thieves' Tools from the SRD Compendium and it works fine. So, might be something in the way DDB-Importer pulls in the Items that could be monkeying with it. I have a work-around for now, but if you figure out what's going wonky I can kick it over to MrPrimate in his Discord as a bug.

**Comment by Saibot393** [comment] 2023-11-25 20:08
I have added improved DDB Importer compatibility with v2.0.9. You will hvae to add this id to the worlds lock picking item IDs: 1279380207. I am not yet 100% certain, that the DDB id i use is the correct one, i will update this issue should i discover any problems.

**Comment by Saibot393** [comment] 2023-11-25 20:21
I was wrong, sorry. The new v2.0.10 should now use the correct id. The id you will have to add to the world settings is 126

**Comment by Saibot393** [comment] 2023-12-12 12:51
I will assume that this bug is solved via the updated id unless i hear back, and will close this issue soon.

**Comment by Geektasticdad** [comment] 2023-12-12 13:55
> I will assume that this bug is solved via the updated id unless i hear back, and will close this issue soon.

Thank you, I think it's fixed.

**Closed** 2023-12-12 14:46 UTC
Labels: bug
