### ISSUE TITLE
"Right-click popup-menu" opening on every token I right click on?

### ISSUE THREAD

**Issue by MastaGooz** [Saibot393/LocknKey#54] opened 2023-11-06 09:14 UTC
When I set "right-click popup-menu" (instead of right-click + key) in the settings, then it open the popup-menu on everything token I right-click on (instead on only showing the popup on things that have a lock).
I tested it without any module and even with different systems, still popin on every token.
Maybe i'm doing something wrong?

**Comment by Saibot393** [comment] 2023-11-06 11:42
I think i now where the problem is, i will release a fix in a few hours

**Comment by Saibot393** [comment] 2023-11-06 16:24
The problem should be fixed with v1.12.5

**Closed by Saibot393** 2023-11-06 16:24 UTC
Labels: bug
