### ISSUE TITLE
Not working with Sandbox system?

### ISSUE THREAD

**Issue by McAwesum00** [Saibot393/LocknKey#16] opened 2023-08-14 21:24 UTC
Hi there. Been trying to use the Lock and Key module with the Sandbox system and I can't seem to get any of the functions to work. I applied the "sword;" key to the "Sword Key" compendium item and also on one of the locked doors, but nothing happens and no pop-ups also occur. I am adding my world from foundry/forge-vtt to test.
[ForgeVTT-export-test-2023-08-14_21_24_13.zip](https://github.com/Saibot393/LocknKey/files/12339688/ForgeVTT-export-test-2023-08-14_21_24_13.zip)

**Comment by Saibot393** [comment] 2023-08-14 21:44
I took a look at the world but it seems quite broken to me (at least in Foundry v10). Since Sandbox is ony officially supported for Foundry v9, i assume thats the version you use? 
In this case there could be a core compatibility issue since Lock & Key is only supported for v10 updwards. I will still take a look at it and see if i can do something about but i can not guarantee for anything.

**Comment by Saibot393** [comment] 2023-08-15 13:57
I just released an update (v1.8.2) which should fix the compatibility issues. Theres were some problems going on with the way inventories are handled in sandbox. Thanks for including the save and the system files in the issue, helped a lot with fixing the problem.

**Comment by McAwesum00** [comment] 2023-08-17 06:38
Nice! I'll check it out ASAP! Thank you!

**Comment by Saibot393** [comment] 2023-08-17 09:55
"cItem" should be the correct one. 
Just to make sure, when shift+right clicking a door no item generated in the item tab, right? In this case, doe any error messages pop up in the console (F12), when doing that?
It could in theory be a problem with other modules interfering, could you send me list of the modules installed?

**Comment by McAwesum00** [comment] 2023-08-17 20:28
Here are all the modules I am using in this game. I'll try and get you some console messages.
![image](https://github.com/Saibot393/LocknKey/assets/139017291/1175e470-5a6d-49bd-b774-f785e9884e85)
![image](https://github.com/Saibot393/LocknKey/assets/139017291/877d73ae-1a44-4974-9dbb-59fb76ece989)
![image](https://github.com/Saibot393/LocknKey/assets/139017291/f5378e2a-8ad1-452b-85f7-5f718ddeb9b6)

**Comment by McAwesum00** [comment] 2023-08-17 20:47
Here is the console commands. It seems like it is creating keys. But I am still not seeing pop-ups. Not sure if the keys are functioning as they are supposed to. but Shift+right click is making keys and new matching IDs.
![image](https://github.com/Saibot393/LocknKey/assets/139017291/2bf71175-75b0-46ba-9454-e5ab4e328877)

**Comment by McAwesum00** [comment] 2023-08-17 21:00
Oh okay. It seems like creating keys with shift+key does create functioning keys for the doors. But I tried copying the key data onto an item I had made previously and using that, and the item wouldn't work. Still not seeing the custom popups when the player tries to open the doors though.

**Comment by Saibot393** [comment] 2023-08-17 22:17
I think i found the problem, i will probably release an update that hopefully fixes the compatibility issues tomorrow

**Comment by McAwesum00** [comment] 2023-08-17 23:44
Great! Looking forward to it! Truly appreciate you responding and working on that so quickly! You are awesome!

**Comment by McAwesum00** [comment] 2023-08-17 23:45
Shoot! Didn't mean to close the issue! Wrong button. haha

**Comment by Saibot393** [comment] 2023-08-18 11:29
I just released v1.9.0 which should (hopefully) fix the compatibility issues, let me know if it worked

**Comment by McAwesum00** [comment] 2023-08-19 01:00
Okay~ After having one of my players help me test. Popup messages worked for lockpicking (shift+rightclick), and door breaking(alt+rightclicking), but not for locked doors (right+clicking). Also, I couldn't get the system to recognize lockpick cItems. When my player tries to open the door it says he's missing the item, even thought I set it in the module settings.

Also, as a request, can there be popup messages if the player attempts to but fails on lockpicking/breaking?

**Comment by Saibot393** [comment] 2023-08-19 11:00
I looked into it and solved the issue with the lockpick items (hopefully, again). 
Regarding the Popups messages for the locked doors, is there no message when a player successfully lock/unlocks a door or if a player tries to unlock a door they do not have a matching key for?

I will add the additional requested popups with the next update (same updated as the bug fixes)

**Comment by McAwesum00** [comment] 2023-08-19 20:54
(in 1.9.0) Messages were popping up when the door was unlocked and locked with the appropriate keys. But the custom popup was not appearing when the door was attempted to be unlocked without the key. 

I guess it makes sense that there would be popups for breaking/picking, but I didn't see them. I'll test the new version later tonight with my friend and see. Thanks again for your vigilance, patience, and hard work!

**Comment by Saibot393** [comment] 2023-08-19 21:36
I just released v1.9.1 which should fix the problem with the lockpick items. 
There is not yet a custom popup for not having  a matching key, there was not even a standard popup (until now). I will add an option for custom popups in the next update.

**Comment by McAwesum00** [comment] 2023-08-20 21:27
Okay after having my player test stuff with me today. 

- It is recognizing that lockpick cItems are needed. So that is fixed.


- Confirmed door says "no matching key" when trying to unlock a door that has no key. No response when a door with an assigned key is attempted to unlock. (Would love to see a custom popup letting players know that door needs a key when they do normal left click.)

- Not recognizing references to sandbox character sheets in lockpicking and breaking formulas. (tried with both @{reference} and @reference formulas) when I try those it either does nothing or just outputs a 0.
 
- When I put in a simple 1d20 formula for lockpicking or breaking, it attempts the rolls twice for some reason. I also see it mention the GM(me) for each roll. Not sure why this is. I had assigned myself as the character for a little while to try to test things by myself, maybe that caused this issue. I had my player screenshot their console for me. 

(first two screenshots are mine. third is from my player)
![image](https://github.com/Saibot393/LocknKey/assets/139017291/913e7a1c-37b3-4b6e-83f4-9d18e95cdf30)
![image](https://github.com/Saibot393/LocknKey/assets/139017291/0d8d4d8e-b73b-4ec7-9924-e2be6435854a)
![image](https://github.com/Saibot393/LocknKey/assets/139017291/0ff29edb-124e-4666-bb02-19e6d4a8ace3)

1. I see this in the console when I have the Right click popup menu option turned on:
![image](https://github.com/Saibot393/LocknKey/assets/139017291/683e0f57-51f0-49aa-a0a6-45f074a31553)

**Comment by Saibot393** [comment] 2023-08-21 15:18
Regarding your points:

1. Good to hear
2. I will add a custom messages for that in the next update
3. I can not quite figure out how to correctly reference skill values in this system, or rather they do not seem to update correctly from my testing so far. How would you for example roll a Handgun check in the chat?
4. I can not reproduce the double rolling behaviour on my end, but i will keep looking, the empty text box with the GMs name was due to some text not being displayed correctly, will be fixed with the next update

**Comment by McAwesum00** [comment] 2023-08-21 18:22
Sandbox is a little weird, it's a system designed to help the GM build their own system and character sheets; so there isn't a universal way to reference skill values. I do know that the main thing that the system does reference a **KEY** on a Property.
![image](https://github.com/Saibot393/LocknKey/assets/139017291/da87cbc9-6bd5-496b-93a0-d178ce644497)
 Most of Sandox works by making new "items" in the Items tab. There several types of items that Sandbox recognizes: **properties, panels, multipanels, sheettabs, groups,** and **citems.**
![image](https://github.com/Saibot393/LocknKey/assets/139017291/2f288574-37d5-47c5-b679-c49b1f4b1897)
 Properties are the main thing to look at when dealing with Sandbox; a property is the basic form of data that the system looks at on a character sheet. If you want to reference a property on a character sheet you usually use **@{key field data}**; so for instance if I made a handun skill and named the Key "handgun" and I wanted to make a roll formula including it, it would probably be **1d20 +@{handgun}**
![image](https://github.com/Saibot393/LocknKey/assets/139017291/0841a3bb-f479-4695-8e27-b9bf42f9b942)
Each property must have a chosen data type that it contains and that usually determines how Sandbox deals with it.
![image](https://github.com/Saibot393/LocknKey/assets/139017291/6d5a7785-899b-46f3-85ea-a73a59f5a786)
Tables are the other way to reference items on a character sheet. Tables deal with "groups" which usually references other properties or cItems. When referencing items in a table the formula changes a little bit. Table properties are referenced by a # instead of an @ symbol. So if I made a handgun cItem and put it in a table I would reference it as **#{handgun}** instead of @{handgun}

As an example. This is the character sheet I made for the game world I sent you that I am currently trying to set up. It is a ttrpg conversion of the Resident Evil Remake video game, but using a rule system that I created, and am using Sandbox to create my character sheets.
![image](https://github.com/Saibot393/LocknKey/assets/139017291/72898636-0988-483d-9af3-9f30a53502db)
As you can see there are several properties that can affect my player's rolls.
1. How many d20s to roll.
2. Whether it's a normal, advantage, or disadvantage roll.
3. If there are any injury penalties applied.
4. My system is modular so I made an editable table that has skills and their skill mods and other bonuses to the roll.

So here is the SkillTableRoll property which contains the formula for die rolls. You can see the references to property keys on the character sheet and skill table.
![image](https://github.com/Saibot393/LocknKey/assets/139017291/f809cb6c-540b-44f7-bbd9-d1edf766198e)


I hope this makes sense and helps. Apologies if it was too longwinded. if you want to learn more about Sandbox; these tutorials were made by the creator and explain how to use it and how it works https://youtube.com/playlist?list=PLMAQsyqo9jDFpHYy4WZv0eF_SgqotcUKs&si=ll2hIdu_f-J3Rq77

**Comment by McAwesum00** [comment] 2023-08-21 18:26
Oh, also as a note a property Key can be made by whomever is making the character sheets or can be autogenerated by Sandbox. There is no universal key for skills or bonuses. It's made by whatever you fill the Key box with. Not sure if I explained that part clearly, but wanted to make sure.

**Comment by Saibot393** [comment] 2023-08-21 18:57
I think i figured out how to theoretically access the values, here written in console code (ignore the yellow warnings):
![image](https://github.com/Saibot393/LocknKey/assets/137942782/19de27ec-87b5-4013-96aa-240a6d18cceb)
As expected the system rolls a d20 and adds the value of Skill1ModL, which can be seen here:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/c6f8c214-5ac1-4097-8798-5a9028ba7537)
This should correspond to the "Handgun" attribut of the character "Seth Ward" (see Skill1NameL above). Now, the problem is, that according to these values "Handgun" should be at a value of 3, which is (strangely) not the case:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/b0ad4182-d9a6-4306-877c-0415ad197784)
Same happens with the api, so it seems to be the right place:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/6e834ac5-10df-47fc-8849-c708889b9b85)
As far as i can see there is also no api function for accessing attributes via their name. 
If the above formula were to work lock break roles could for example be done like this:
![image](https://github.com/Saibot393/LocknKey/assets/137942782/aa883408-1549-4a9d-9484-7056f4cd3642)
I am currently a bit stuck but i will investigate further.

**Comment by Saibot393** [comment] 2023-08-21 19:11
Ok, figured it out, the roll formula to reference the first attribute would look like this:
@actor.system.attributes.TBL_SKILLSTABLE.tableitems.0.attributes.skillmod.value
Replace the 0 with the position in the Skill table (starting at 0) to reference the different attributes of a character.
I don't think i can build a system to reference values easier (or by name) due to the modularity of Sanbox, so this way of referencing will probably have to suffice

**Comment by McAwesum00** [comment] 2023-08-21 20:28
yeah, I understand that the modularity makes it a lot trickier to deal with, so I wasn't expecting a super perfect solution. Just was hoping to see if we could get some base functionality of it recognizing properties or something~ Excited to try out the next build!

**Comment by Saibot393** [comment] 2023-08-21 20:48
I just released v1.9.2, which should fix two bugs:

1. The previuosly empty chat box with the GMs name should now have the correct content
2. The custom popup for lefclicking a locked door should now be displayed correctly

Since i cannot reproduce the double rolling bug, i will probably need your world file to figure out what exactly is happening

**Comment by McAwesum00** [comment] 2023-08-23 10:19
1. Whatever changes you made seemed to have fixed the double roll issue. So that's gone.
2. the formula for accessing the character sheet is working the way you wrote it. 
3. however, I would love to be able to access the Roll Formulas in the properties as the formulas for the lockpick/breaking formulas. Not sure if you could get that to function or not~
![image](https://github.com/Saibot393/LocknKey/assets/139017291/459753e5-b3ef-497c-b975-949164929885)
4. I  not seeing the popup messages when leftclicking a door.

Here is my world if you need it still:
[ForgeVTT-export-test-2023-08-23_9_47_10.zip](https://github.com/Saibot393/LocknKey/files/12417775/ForgeVTT-export-test-2023-08-23_9_47_10.zip)

**Comment by Saibot393** [comment] 2023-08-24 10:22
Regarding 3.: The problem is the modular nature of the module. I would have to write additional code to even reach these formulas (that could break for different worlds/character sheets) and then write an interpreter for the rolls themself (as far as i can see there Synbox provides no api for that). Both of these (and especially the last) are bit out of scope for this. So i will probably not be able to include a feature for that, sorry.
Regarding 4.: SHould be fixed with v1.9.5

**Comment by McAwesum00** [comment] 2023-08-24 23:00
3. Totally understand! I kind of figured as much, but thought I would bring it up just in case! I am honestly amazed you even put in as much effort and work as you already have in order to get Sandbox working with the module as is! You rock!
4. I'll check it as soon as i can!

**Comment by McAwesum00** [comment] 2023-08-25 20:45
Okay! Just checked with my players and it seems like the popup messages are working correctly now! Thank you for everything!

**Comment by Saibot393** [comment] 2023-08-26 09:16
Good to hear that everything works now, should any more problems arise, feel free to add to this issee or open a new one. I will close this issue for now.

**Closed by Saibot393** 2023-08-26 09:16 UTC
Labels: bug
